### ISSUE TITLE
it seems to have a problem installing it on laravel 8.65

### ISSUE THREAD

**Issue by jadShartouny** [spatie/laravel-webhook-server#111]
whilte trying to use it with my laravel 8 app i got this error.

Problem 1
    - spatie/laravel-webhook-server 1.4.0 requires guzzlehttp/guzzle ^6.3 -> found guzzlehttp/guzzle[6.3.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).
    - spatie/laravel-webhook-server[1.5.0, ..., 1.10.0] require php ^7.4 -> your php version (7.3.33) does not satisfy that requirement.
    - spatie/laravel-webhook-server[1.11.0, ..., 1.13.0] require php ^8.0|^7.4 -> your php version (7.3.33) does not satisfy that requirement.
    - Root composer.json requires spatie/laravel-webhook-server ^1.4 -> satisfiable by spatie/laravel-webhook-server[1.4.0, ..., 1.13.0].

**Comment by freekmurze** [comment]
This isn't an issue with the package code itself, please create a discussion.
