### ISSUE TITLE
Tags are not visible in Horizon

### ISSUE THREAD

**Issue by lasselehtinen** [spatie/laravel-webhook-server#118]
Seems like the tags are not visible in Horizon as they should, even though they are set? Using Horizon v5.9.3.

![image](https://user-images.githubusercontent.com/1290186/160353174-bcf8d578-e9d0-411d-ba49-49fc461ce602.png)

![image](https://user-images.githubusercontent.com/1290186/160353257-bdc0e416-939a-4afd-9914-65a8092d5ab5.png)

**Comment by freekmurze** [comment]
Mmm, strange, ... If you know the fix, feel free to send a PR.
