### ISSUE TITLE
Possibility to send XML and Form Data

### ISSUE THREAD

**Issue by oliverbj** [spatie/laravel-webhook-server#13]
Hi

I was wondering if it's possible to send XML data with this package instead of an array?

For example:

```php
$payload = '<document><id>1</id></document>';
WebhookCall::create()
            ->url('myurl.com')
            ->payload($payload)
            ->useSecret('change-me-to-something-else')
            ->dispatch();

```

Right now, I get an error message saying that I must specify an array:

```
Argument 1 passed to Spatie\WebhookServer\WebhookCall::payload() must be of the type array, string given, in [...]
```

I am a bit new to PHP and Laravel in general, but I was wondering if it was possible to extend this package to be able to send `text/xml` and `application/x-www-form-urlencoded` by creating my own signers? 

For example:

```php
WebhookCall::create()
    ->signUsing(XMLSigner::class) // or FormSigner::class
    ...
    ->dispatch();
```

**Comment by freekmurze** [comment]
Currently this is not possible. Because I don’t have a need for this myself, I’m not going to invest time in this. If you can add support for this in a simple, testable way, feel free to PR it to the package.

**Comment by brad-tilmor** [comment]
While I understand not wanting to add XML or form data capabilities to this, I would find it extremely valuable to be able to send API resources as json rather than arrays to avoid the need to do weird type juggling in order to send webhooks. Just my 2 cents.
