### ISSUE TITLE
MaxAttemptsExceededException: CallWebhookJob has been attempted too many times 

### ISSUE THREAD

**Issue by dmason30** [spatie/laravel-webhook-server#17]
**Description**
I have set the config `webhook-server.tries` to `1`  ended up getting this exception when the webhook request failed:

````
Illuminate\Queue\MaxAttemptsExceededException: Spatie\WebhookServer\CallWebhookJob 
has been attempted too many times or run too long. 
The job may have previously timed out. 
in /var/www/services/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:595
````

**Cause**
On webhook request failure the job is released on every attempt (including the last one):

_CallWebhookJob_
```
} catch (Exception $exception) {
    /** @var \Spatie\WebhookServer\BackoffStrategy\BackoffStrategy $backoffStrategy */
    $backoffStrategy = app($this->backoffStrategyClass);
    $waitInSeconds = $backoffStrategy->waitInSecondsAfterAttempt($this->attempts());
    $this->dispatchEvent(WebhookCallFailedEvent::class);
    $this->release($waitInSeconds);
}
```

But after the catch it detects if it is the last attempt and does delete the job. 

```
if ($this->attempts() >= $this->tries) {
    $this->dispatchEvent(FinalWebhookCallFailedEvent::class);
    $this->delete();
}
```

But since the job was released before the queue tries to process it and then throws the above exception. 

**Solution**
Do not run the backoff strategy/release on the last attempt. 

See PR #18

**Comment by freekmurze** [comment]
We'll continue this conversation in #18
