### ISSUE TITLE
Where the queue should running?

### ISSUE THREAD

**Issue by wellyrm** [spatie/laravel-webhook-server#27]
Is the queue running on the server or the client?
In my application, it is run on the server and the webhook never received by the client.

I create a helper, here is the content

```
class SendWebhooks {
    public static function send($key,$data,$destination=null) {
        if($destination) $url = $destination;
        else $url = env('WEBHOOK_CLIENT_URL');
    
        WebhookCall::create()
            ->url($url)
            ->payload([$key=>$data])
            ->useSecret(env('WEBHOOK_CLIENT_SECRET'))
            ->dispatch();
    }
}
```

And this how I call the helper in controller
```
$product = Products::get();
SendWebhooks::send('product',$product);
```

is there anything wrong with my code?

**Comment by freekmurze** [comment]
Could looks find. Do you send any outgoing requests from your app if you use the `sync` queue driver?

**Comment by wellyrm** [comment]
Changed queue driver to `sync` and the queue is clean now. I mean, not show any webhookcall queue when the command run.

Here's the queue in webhook server if I use redis:
```
Processing: Spatie\WebhookServer\CallWebhookJob
Processed:  Spatie\WebhookServer\CallWebhookJob
```

**Comment by freekmurze** [comment]
Try adding a dd statement inside the dispatch method of the package. Is that code reached?

**Comment by wellyrm** [comment]
I got this:
```
PendingDispatch {#723 ▼
  #job: CallWebhookJob {#706 ▼
    +webhookUrl: "http://localhost:8001/webhook-receiver"
    +httpVerb: "post"
    +tries: 3
    +requestTimeout: 3
    +backoffStrategyClass: "Spatie\WebhookServer\BackoffStrategy\ExponentialBackoffStrategy"
    +signerClass: null
    +headers: array:2 [▶]
    +verifySsl: true
    +queue: "default"
    +payload: array:1 [▶]
    +meta: []
    +tags: []
    -response: null
    -errorType: null
    -errorMessage: null
    #job: null
    +connection: null
    +chainConnection: null
    +chainQueue: null
    +delay: null
    +middleware: []
    +chained: []
  }
}
```
It's reached...

**Comment by wellyrm** [comment]
@upwebdesign yes. I running both on server and client.

**Comment by augustinejenin** [comment]
I get this error when i try to install  Package spatie/laravel-webhook-server at version  has a PHP requirement incompatible with your PHP version (7.2.4)

**Comment by upwebdesign** [comment]
@augustinejenin this package requires PHP ^7.3
