### ISSUE TITLE
What is the supported version?

### ISSUE THREAD

**Issue by thexcats** [spatie/laravel-webhook-server#28]
Good afternoon, I am writing to you from Chile, I would like to know what version of PHP the plugin needs, both the server and the client, because I have version 7.1.32 and wanting to install via "composer" did not allow me for the PHP version, in advance thank you very much.

P.D: the error that appeared to me is the following

  [InvalidArgumentException]
   Could not find package spatie / laravel-webhook-server in any version matching your PHP version (7.1.32)

**Comment by freekmurze** [comment]
You'll need PHP 7.3

https://github.com/spatie/laravel-webhook-server/blob/master/composer.json#L21
