### ISSUE TITLE
How do you add listeners for the events?

### ISSUE THREAD

**Issue by khan-zia** [spatie/laravel-webhook-server#29]
Perhaps, I am out of luck or something but I haven't been able to listen on the events fired by the package. I have tried manually registering inside EventServiceProvider, I have tried registering in the $listen array by using *Spatie\WebhookServer\Events\* as the Event. Here is what I have tried.

```
       '\Spatie\WebhookServer\Events\WebhookCallSucceededEvent' => [
            'App\Listeners\LogLogoutWebhookCallSuccess',
        ],
        '\Spatie\WebhookServer\Events\WebhookCallFailedEvent' => [
            'App\Listeners\LogLogoutWebhookCallFailure',
        ],
        '\Spatie\WebhookServer\Events\FinalWebhookCallFailedEvent' => [
            'App\Listeners\LogLogoutWebhookCallFinalFailure',
        ],
```

Also tried this

```
       '\Spatie\WebhookServer\Events\WebhookCallSucceededEvent' => [
            'Spatie\WebhookServer\Listeners\LogLogoutWebhookCallSuccess',
        ],
        '\Spatie\WebhookServer\Events\WebhookCallFailedEvent' => [
            'Spatie\WebhookServer\Listeners\LogLogoutWebhookCallFailure',
        ],
        '\Spatie\WebhookServer\Events\FinalWebhookCallFailedEvent' => [
            'Spatie\WebhookServer\Listeners\LogLogoutWebhookCallFinalFailure',
        ],
```

It doesn't work. Somebody please help and also it would be very nice to add the information to the README.md on the repo. Thanks

**Comment by freekmurze** [comment]
Hi, the package surely sends out the events, it's covered by our test suite. To learn how to listen for them, head over to the laravel docs. https://laravel.com/docs/6.x/events#defining-listeners

Should you still have problems, head over to a public forum such as laracasts and ask for help.

It it turns out that this package contains an error, submit a PR.

**Comment by pakcybershagufta** [comment]
App\Providers\EventServiceProvider::class


register in service provider  else it will not work

**Comment by pakcybershagufta** [comment]
protected $listen = [
        'Spatie\WebhookServer\Events\FinalWebhookCallFailedEvent' => [
            'App\Listeners\ExampleListener',
        ],'Spatie\WebhookServer\Events\WebhookCallFailedEvent' => [
            'App\Listeners\Example2Listener',
        ],
    ];

**Comment by tamsir** [comment]
I try this code but no result
