### ISSUE TITLE
Lumen 5.8: Trait 'Illuminate\Foundation\Bus\Dispatchable' not found

### ISSUE THREAD

**Issue by judgej** [spatie/laravel-webhook-server#3]
It seems that the `Illuminate\Foundation\Bus\Dispatchable` trait does not exist on Lumen. I'm also not entirely sure whether your package actually makes use of the trait. Removing the `Dispatchable` trait from `CallWebhookJob` allows the package to work on Lumen 5.8.

https://github.com/spatie/laravel-webhook-server/blob/master/src/CallWebhookJob.php

The Laravel documentation is not clear why this trait is not present. The Lumen docs just say, "go see the Laravel docs, it's the same". But it obviously isn't.

**Comment by freekmurze** [comment]
Dispatchable allows for some Laravel related niceties such as chaining. I'm going to leave it on the job for now. Because we don't use Lumen at our firm, we're not going to support it.

Feel free to fork the package 👍

**Comment by judgej** [comment]
Thanks, forked here, in case anyone else has this issue:

https://github.com/consilience/laravel-webhook-server

**Comment by georgeboot** [comment]
Can't we create an abstract class `CallWebhookJobAbstract` with two subclasses: `CallWebhookJob` (including `Dispatchable` to remain bc) and a `CallWebhookJobLumen` without the trait?

**Comment by judgej** [comment]
Just spotted you forked for the same reason here @georgeboot 

https://github.com/georgeboot/laravel-webhook-server/commit/ad24e66cd341a199f663c43611c7408f1fd62ec3

**Comment by georgeboot** [comment]
> Just spotted you forked for the same reason here @georgeboot 

yeah indeed. Actually made some changes so it works a bit nicer with Lumen. Did a PR (#5) but that was declined for understandable reasons.
