### ISSUE TITLE
Local use with laravel valet leads to silently failure due to domain unresolved curl error

### ISSUE THREAD

**Issue by thoresuenert** [spatie/laravel-webhook-server#34]
Hey thanks for this great package. saves a lot of time.

I run into curl error which was not so obvious to debug, see this as a reminder/lookup for other developer.
Switching to `artisan serve` everything works as aspected.

**Debugging process**

- I had the standard setup with `sync queue driver` and didn't get any feedback.
- after implementing `database queue driver` I saw multiple attempts.
- After implementing a listen for `WebhookCallFailedEvent` I was able to log the error message:

```
local.DEBUG: cURL error 6: Could not resolve: test-message-queue.localhost (Domain name not found) (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) 
```

Hopefully this will save time for others.

**Comment by freekmurze** [comment]
Thanks!

**Comment by jartaud** [comment]
To others:
If you're testing your webhook body locally, don't forget to add your URI to `VerifyCsrfToken::$except[]` to avoid getting 419 Unknown Error.
