### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by lvandyk** [spatie/laravel-webhook-server#36]
Hi!

Suddenly started getting 

`syntax error, unexpected 'CallWebhookJob' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)` in line 13 of `/var/www/vendor/spatie/laravel-webhook-server/src/WebhookCall.php`

Invoked simply by doing: `WebhookCall::create()`

Thought it might be my PHP version but it was working 100% earlier. Running PHP 7.3.

Any thoughts on what it could be?

**Comment by freekmurze** [comment]
It seems like you pulled it an incompatible version. The latest version requires PHP 7.4.
Take a look in our change log when we added that requirement and let composer pull in the version before that one.

**Comment by lvandyk** [comment]
Awesome thanks for the quick reply @freekmurze

**Comment by ultrasamad** [comment]
I'm getting same error. 
Using version `1.9.1` and PHP version `7.4`
