### ISSUE TITLE
No query results for model [Spatie\WebhookClient\Models\WebhookCall]

### ISSUE THREAD

**Issue by averageflow** [spatie/laravel-webhook-server#38]
Hello Spatie team, I am using your package and really find it great, works perfectly, thing is when I run it in my MacBook I don't get any issues, but when I deploy to production, some of my webhook calls throw this error, not all of them, that is why I am a bit puzzled, what does this mean? How could I fix it? Missing something?

`

Illuminate\Database\Eloquent\ModelNotFoundException:  No query results for model [Spatie\WebhookClient\Models\WebhookCall].  in  /webstore/api/releases/v-1.1.2/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:470
--
Stack trace:
#0   /webstore/api/releases/v-1.1.2/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(102):  Illuminate\Database\Eloquent\Builder->firstOrFail()
#1   /webstore/api/releases/v-1.1.2/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(57):   Spatie\WebhookClient\ProcessWebhookJob->restoreModel(Object(Illuminate\Contracts\Database\ModelIdentifier))
#2   /webstore/api/releases/v-1.1.2/vendor/laravel/framework/src/Illuminate/Queue/SerializesModels.php(45):   Spatie\WebhookClient\ProcessWebhookJob->getRestoredPropertyValue(Object(Illuminate\Contracts\Database\ModelIdentifier))
#3 [internal function]: Spatie\WebhookClient\ProcessWebhookJob->__wakeup()
#4   /webstore/api/releases/v-1.1.2/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(53):  unserialize('O:35:"Infrastru...')
#5   /webstore/api/releases/v-1.1.2/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(88):   Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob),  Array)
#6   /webstore/api/releases/v-1.1.2/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(368):  Illuminate\Queue\Jobs\Job->fire()
#7   /webstore/api/releases/v-1.1.2/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(314):  Illuminate\Queue\Worker->process('redis',  Object(Illuminate\Queue\Jobs\RedisJob),  Object(Illuminate\Queue\WorkerOptions))
#8   /webstore/api/releases/v-1.1.2/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(134):   Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob),  'redis', Object(Illuminate\Queue\WorkerOptions))
#9   /webstore/api/releases/v-1.1.2/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112):  Illuminate\Queue\Worker->daemon('redis', 'default,priorit...',  Object(Illuminate\Queue\WorkerOptions))
#10   /webstore/api/releases/v-1.1.2/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96):  Illuminate\Queue\Console\WorkCommand->runWorker('redis',  'default,priorit...')
#11   /webstore/api/releases/v-1.1.2/vendor/laravel/horizon/src/Console/WorkCommand.php(46):  Illuminate\Queue\Console\WorkCommand->handle()
#12 [internal function]: Laravel\Horizon\Console\WorkCommand->handle()
#13   /webstore/api/releases/v-1.1.2/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32):  call_user_func_array(Array, Array)
#14   /webstore/api/releases/v-1.1.2/vendor/laravel/framework/src/Illuminate/Container/Util.php(36):  Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#15   /webstore/api/releases/v-1.1.2/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90):  Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#16   /webstore/api/releases/v-1.1.2/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34):   Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application),  Array, Object(Closure))
#17   /webstore/api/releases/v-1.1.2/vendor/laravel/framework/src/Illuminate/Container/Container.php(590):   Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application),  Array, Array, NULL)
#18   /webstore/api/releases/v-1.1.2/vendor/laravel/framework/src/Illuminate/Console/Command.php(134):  Illuminate\Container\Container->call(Array)
#19   /webstore/api/releases/v-1.1.2/vendor/symfony/console/Command/Command.php(255):   Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput),  Object(Illuminate\Console\OutputStyle))
#20   /webstore/api/releases/v-1.1.2/vendor/laravel/framework/src/Illuminate/Console/Command.php(121):   Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput),  Object(Illuminate\Console\OutputStyle))
#21   /webstore/api/releases/v-1.1.2/vendor/symfony/console/Application.php(1012):   Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput),  Object(Symfony\Component\Console\Output\ConsoleOutput))
#22   /webstore/api/releases/v-1.1.2/vendor/symfony/console/Application.php(272):   Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand),  Object(Symfony\Component\Console\Input\ArgvInput),  Object(Symfony\Component\Console\Output\ConsoleOutput))
#23   /webstore/api/releases/v-1.1.2/vendor/symfony/console/Application.php(148):   Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput),  Object(Symfony\Component\Console\Output\ConsoleOutput))
#24   /webstore/api/releases/v-1.1.2/vendor/laravel/framework/src/Illuminate/Console/Application.php(93):   Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput),  Object(Symfony\Component\Console\Output\ConsoleOutput))
#25   /webstore/api/releases/v-1.1.2/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131):   Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput),  Object(Symfony\Component\Console\Output\ConsoleOutput))
#26  /webstore/api/releases/v-1.1.2/artisan(37):  Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput),  Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 {main}

`

**Comment by averageflow** [comment]
I am assuming this means something along the lines of not being able to find a record that was in the webhool_calls database table?

**Comment by chintan-benzatine** [comment]
Location :- Handle Exception: app/Exceptions/Handler.php

<?php

namespace App\Exceptions;

use Exception;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Database\Eloquent\ModelNotFoundException;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'password',
        'password_confirmation',
    ];

    /**
     * Report or log an exception.
     *
     * @param  \Exception  $exception
     * @return void
     *
     * @throws \Exception
     */
    public function report(Exception $exception)
    {
        parent::report($exception);
    }

    /**
     * Render an exception into an HTTP response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Exception  $exception
     * @return \Symfony\Component\HttpFoundation\Response
     *
     * @throws \Exception
     */
    // public function render($request, Exception $exception)
    // {
    //     return parent::render($request, $exception);
    // }
    public function render($request, Exception $exception)
    {
        if ($exception instanceof ModelNotFoundException) {
            return response()->json(['message' => 'Data not found.']);
        }

        return parent::render($request, $exception);
    }
}

**Comment by chintan-benzatine** [comment]
public function render($request, Exception $exception)
    {
        if ($exception instanceof ModelNotFoundException) {
            return response()->json(['message' => 'Data not found.']);
        }

        return parent::render($request, $exception);
    }
