### ISSUE TITLE
Missing 'Content-Type: application/json' header

### ISSUE THREAD

**Issue by stefanzweifel** [spatie/laravel-webhook-server#4]
While testing the package in two Laravel 5.8 apps, we ran into a very basic issue: The payload from the Webhook Request couldn't be parsed by the Webhook Client.

We could pinpoint the issue to a missing `Content-Type: application/json`-header in [CallWebhookJob](https://github.com/spatie/laravel-webhook-server/blob/d7ab7af861deed0e3bc84f1ad43f3febe74c938b/src/CallWebhookJob.php#L70).

Adding the header in `webhook-server.headers` configuration fixed the problem.

```php
/*
 * These are the headers that will be added to all webhook requests.
 */
'headers' => [
    'Content-Type' => 'application/json'
],
```

Is there a reason the header is not added by default? If not, could the header be added automatically by the package itself?

(Both apps run on the latest versions of both packages.)

**Comment by Stokoe0990** [comment]
I would assume it isn't added by default to allow individual use cases where there may be alternate content-types being used.

Having a default configuration value would make sense though.

**Comment by freekmurze** [comment]
I'l add this in the default config file.
