### ISSUE TITLE
Question about uuid...

### ISSUE THREAD

**Issue by telkins** [spatie/laravel-webhook-server#41]
Quick question about the `uuid` value.  It doesn't seem to be a part of the payload.  Is there an easy way to make it a part of the payload?  Or am I missing something?  ;-)

Thx.

**Comment by freekmurze** [comment]
We don't add that by default to the payload. If you want the uuid to be part of the payload, you'll have to manually generate a uuid an pass it to `uuid` and the payload.

```
WebhookCall::create()
   ->uuid($yourUuid)
  ->payload(['uuid' => $yourUuid])
  -> ...
```

**Comment by telkins** [comment]
Thx.  :-)
