### ISSUE TITLE
CloudFront responds 403 to GET requests with a body

### ISSUE THREAD

**Issue by dmason30** [spatie/laravel-webhook-server#42]
**Problem**
We recently found an issue with using this package to send a GET request to a site deployed with vapor. 

In our 'webhook server' we are sending this request to a number of other sites successfully. However, after a bit of research I came across this SO question:

https://stackoverflow.com/questions/55910096/are-get-request-with-body-allowed-on-aws-403-error-from-cloudfront

With the answer:

> GET request with Body is not allowed on CloudFront, You will get 403 if you send body, though RFC does not specifically say that you should reject GET with body but CloudFront doesn't allow that. The best option to pass body in GET request is by query string(Maximum length of a request, including headers and query strings 20,480 bytes).
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html
GET Requests That Include a Body If a viewer GET request includes a body, CloudFront returns an HTTP status code 403 (Forbidden) to the viewer.

**Solution**
Our get request does not even have a payload but after a bit of debugging I realised the 'body' was being sent with an empty array as that is the default payload value. 

I have tested the below change that works as expected by changing `body` to `query` when doing a `GET` request:

_CallWebhookJob.php_
```php
$body = $this->httpVerb == 'GET'
    ? ['query' => $this->payload]
    : ['body' => json_encode($this->payload)];

$this->response = $client->request($this->httpVerb, $this->webhookUrl, array_merge([
    'timeout' => $this->requestTimeout,
    'verify' => $this->verifySsl,
    'headers' => $this->headers,
], $body));
```

**If this is something you are happy to proceed with I will create a PR with tests!**

**Comment by freekmurze** [comment]
Yup, send a PR that fixes this 👍
