### ISSUE TITLE
Appending custom headers to specific webhooks

### ISSUE THREAD

**Issue by chyupa** [spatie/laravel-webhook-server#44]
There is the possibility to define the Headers for all requests in the config file: `webhook-server.php`. Which works as intended.

However, using the `withHeaders` method to append extra Headers (besides the ones added in the config file), it will override those and the request will only contain the `Signature` and the 'custom headers' added.

**Comment by freekmurze** [comment]
I'd accept a PR that adds  `appendToDefaultHeaders(array $headers)` that does what you expect. Make sure to include tests.
