### ISSUE TITLE
Add support for laravel 7

### ISSUE THREAD

**Issue by palaciosdiego** [spatie/laravel-webhook-server#45]
- spatie/laravel-webhook-server 1.4.0 requires illuminate/bus ^5.8|^6.0 -> satisfiable by laravel/framework[6.x-dev]

**Comment by khan-zia** [comment]
Hey @palaciosdiego , Support for laravel 7 has been added in [1.6 release](https://github.com/spatie/laravel-webhook-server/releases/tag/1.6.0). Please update to latest version which at the moment is 1.9.1 and close the issue.
