### ISSUE TITLE
ParseError in vendor/spatie/laravel-webhook-server/src/Events/WebhookCallEvent.php

### ISSUE THREAD

**Issue by pakcybershagufta** [spatie/laravel-webhook-server#49]
php 7.4

I am getting this syntax error 
{
    "message": "syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)",
    "exception": "ParseError",
    "file": "/var/www/html/layaway/vendor/spatie/laravel-webhook-server/src/Events/WebhookCallEvent.php",
    "line": 9,
    "trace": [
        {
            "file": "/var/www/html/layaway/vendor/composer/ClassLoader.php",
            "line": 322,
            "function": "Composer\\Autoload\\includeFile"
        },
        {
            "function": "loadClass",
            "class": "Composer\\Autoload\\ClassLoader",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/spatie/laravel-webhook-server/src/Events/WebhookCallFailedEvent.php",
            "line": 5,
            "function": "spl_autoload_call"
        },
        {
            "file": "/var/www/html/layaway/vendor/composer/ClassLoader.php",
            "line": 444,
            "function": "include"
        },
        {
            "file": "/var/www/html/layaway/vendor/composer/ClassLoader.php",
            "line": 322,
            "function": "Composer\\Autoload\\includeFile"
        },
        {
            "function": "loadClass",
            "class": "Composer\\Autoload\\ClassLoader",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/jmsfwk/lumen-webhook-server/src/CallWebhookJob.php",
            "line": 109,
            "function": "spl_autoload_call"
        },
        {
            "file": "/var/www/html/layaway/vendor/jmsfwk/lumen-webhook-server/src/CallWebhookJob.php",
            "line": 95,
            "function": "dispatchEvent",
            "class": "Jmsfwk\\WebhookServer\\CallWebhookJob",
            "type": "->"
        },
        {
            "function": "handle",
            "class": "Jmsfwk\\WebhookServer\\CallWebhookJob",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/illuminate/container/BoundMethod.php",
            "line": 33,
            "function": "call_user_func_array"
        },
        {
            "file": "/var/www/html/layaway/vendor/illuminate/container/Util.php",
            "line": 36,
            "function": "Illuminate\\Container\\{closure}",
            "class": "Illuminate\\Container\\BoundMethod",
            "type": "::"
        },
        {
            "file": "/var/www/html/layaway/vendor/illuminate/container/BoundMethod.php",
            "line": 91,
            "function": "unwrapIfClosure",
            "class": "Illuminate\\Container\\Util",
            "type": "::"
        },
        {
            "file": "/var/www/html/layaway/vendor/illuminate/container/BoundMethod.php",
            "line": 35,
            "function": "callBoundMethod",
            "class": "Illuminate\\Container\\BoundMethod",
            "type": "::"
        },
        {
            "file": "/var/www/html/layaway/vendor/illuminate/container/Container.php",
            "line": 592,
            "function": "call",
            "class": "Illuminate\\Container\\BoundMethod",
            "type": "::"
        },
        {
            "file": "/var/www/html/layaway/vendor/illuminate/bus/Dispatcher.php",
            "line": 94,
            "function": "call",
            "class": "Illuminate\\Container\\Container",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/illuminate/pipeline/Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Bus\\{closure}",
            "class": "Illuminate\\Bus\\Dispatcher",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/illuminate/pipeline/Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/illuminate/bus/Dispatcher.php",
            "line": 98,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/illuminate/queue/CallQueuedHandler.php",
            "line": 83,
            "function": "dispatchNow",
            "class": "Illuminate\\Bus\\Dispatcher",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/illuminate/pipeline/Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Queue\\{closure}",
            "class": "Illuminate\\Queue\\CallQueuedHandler",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/illuminate/pipeline/Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/illuminate/queue/CallQueuedHandler.php",
            "line": 85,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/illuminate/queue/CallQueuedHandler.php",
            "line": 59,
            "function": "dispatchThroughMiddleware",
            "class": "Illuminate\\Queue\\CallQueuedHandler",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/illuminate/queue/Jobs/Job.php",
            "line": 98,
            "function": "call",
            "class": "Illuminate\\Queue\\CallQueuedHandler",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/illuminate/queue/SyncQueue.php",
            "line": 43,
            "function": "fire",
            "class": "Illuminate\\Queue\\Jobs\\Job",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/illuminate/queue/Queue.php",
            "line": 46,
            "function": "push",
            "class": "Illuminate\\Queue\\SyncQueue",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/illuminate/bus/Dispatcher.php",
            "line": 175,
            "function": "pushOn",
            "class": "Illuminate\\Queue\\Queue",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/illuminate/bus/Dispatcher.php",
            "line": 158,
            "function": "pushCommandToQueue",
            "class": "Illuminate\\Bus\\Dispatcher",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/illuminate/bus/Dispatcher.php",
            "line": 73,
            "function": "dispatchToQueue",
            "class": "Illuminate\\Bus\\Dispatcher",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/laravel/lumen-framework/src/Bus/PendingDispatch.php",
            "line": 60,
            "function": "dispatch",
            "class": "Illuminate\\Bus\\Dispatcher",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/laravel/lumen-framework/src/helpers.php",
            "line": 111,
            "function": "__destruct",
            "class": "Laravel\\Lumen\\Bus\\PendingDispatch",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/jmsfwk/lumen-webhook-server/src/WebhookCall.php",
            "line": 169,
            "function": "dispatch"
        },
        {
            "file": "/var/www/html/layaway/app/Http/Controllers/v1/UserController.php",
            "line": 134,
            "function": "dispatch",
            "class": "Jmsfwk\\WebhookServer\\WebhookCall",
            "type": "->"
        },
        {
            "function": "hook",
            "class": "App\\Http\\Controllers\\v1\\UserController",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/illuminate/container/BoundMethod.php",
            "line": 33,
            "function": "call_user_func_array"
        },
        {
            "file": "/var/www/html/layaway/vendor/illuminate/container/Util.php",
            "line": 36,
            "function": "Illuminate\\Container\\{closure}",
            "class": "Illuminate\\Container\\BoundMethod",
            "type": "::"
        },
        {
            "file": "/var/www/html/layaway/vendor/illuminate/container/BoundMethod.php",
            "line": 91,
            "function": "unwrapIfClosure",
            "class": "Illuminate\\Container\\Util",
            "type": "::"
        },
        {
            "file": "/var/www/html/layaway/vendor/illuminate/container/BoundMethod.php",
            "line": 35,
            "function": "callBoundMethod",
            "class": "Illuminate\\Container\\BoundMethod",
            "type": "::"
        },
        {
            "file": "/var/www/html/layaway/vendor/illuminate/container/Container.php",
            "line": 592,
            "function": "call",
            "class": "Illuminate\\Container\\BoundMethod",
            "type": "::"
        },
        {
            "file": "/var/www/html/layaway/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php",
            "line": 376,
            "function": "call",
            "class": "Illuminate\\Container\\Container",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php",
            "line": 342,
            "function": "callControllerCallable",
            "class": "Laravel\\Lumen\\Application",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php",
            "line": 316,
            "function": "callLumenController",
            "class": "Laravel\\Lumen\\Application",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php",
            "line": 278,
            "function": "callControllerAction",
            "class": "Laravel\\Lumen\\Application",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php",
            "line": 263,
            "function": "callActionOnArrayBasedRoute",
            "class": "Laravel\\Lumen\\Application",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php",
            "line": 165,
            "function": "handleFoundRoute",
            "class": "Laravel\\Lumen\\Application",
            "type": "->"
        },
        {
            "function": "Laravel\\Lumen\\Concerns\\{closure}",
            "class": "Laravel\\Lumen\\Application",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/laravel/lumen-framework/src/Routing/Pipeline.php",
            "line": 48,
            "function": "call_user_func"
        },
        {
            "file": "/var/www/html/layaway/vendor/illuminate/cookie/Middleware/AddQueuedCookiesToResponse.php",
            "line": 37,
            "function": "Laravel\\Lumen\\Routing\\{closure}",
            "class": "Laravel\\Lumen\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/illuminate/pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse",
            "type": "->"
        },
        {
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/laravel/lumen-framework/src/Routing/Pipeline.php",
            "line": 30,
            "function": "call_user_func"
        },
        {
            "file": "/var/www/html/layaway/vendor/illuminate/pipeline/Pipeline.php",
            "line": 103,
            "function": "Laravel\\Lumen\\Routing\\{closure}",
            "class": "Laravel\\Lumen\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php",
            "line": 413,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php",
            "line": 171,
            "function": "sendThroughPipeline",
            "class": "Laravel\\Lumen\\Application",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php",
            "line": 108,
            "function": "dispatch",
            "class": "Laravel\\Lumen\\Application",
            "type": "->"
        },
        {
            "file": "/var/www/html/layaway/public/index.php",
            "line": 28,
            "function": "run",
            "class": "Laravel\\Lumen\\Application",
            "type": "->"

        }
    ]
}

**Comment by pakcybershagufta** [comment]
when i comment few lines like below it start working

<?php

namespace Spatie\WebhookServer\Events;

use GuzzleHttp\Psr7\Response;

abstract class WebhookCallEvent
{
    //   $httpVerb;

    // public string $webhookUrl;

    // public array $payload;

    // public array $headers;

    // public array $meta;

    // public array $tags;

    // public int $attempt;

    // public ?Response $response;

    // public ?string $errorType;

    // public ?string $errorMessage;

   // public string $uuid;

    public function __construct(
        string $httpVerb,
        string $webhookUrl,
        array $payload,
        array $headers
        // ,array $meta,
        // array $tags,
        // int $attempt,
        // ?Response $response,
        // ?string $errorType,
        // ?string $errorMessage,
        // string $uuid
    ) {
        $this->httpVerb = $httpVerb;
        $this->webhookUrl = $webhookUrl;
        $this->payload = $payload;
        $this->headers = $headers;
        // $this->meta = $meta;
        // $this->tags = $tags;
        // $this->attempt = $attempt;
        // $this->response = $response;
        // $this->errorType = $errorType;
        // $this->errorMessage = $errorMessage;
        // $this->uuid = $uuid;
    }
}

**Comment by freekmurze** [comment]
Please make sure you have PHP 7.4. Read this blog post carefully: https://freek.dev/1598-how-to-check-which-version-of-php-you-are-running

**Comment by pakcybershagufta** [comment]
php -v
PHP 7.4.7 (cli) (built: Jun 12 2020 07:44:05) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.7, Copyright (c), by Zend Technologies
