### ISSUE TITLE
 WebhookCall::create response

### ISSUE THREAD

**Issue by pakcybershagufta** [spatie/laravel-webhook-server#51]
WEBHOOK Create response

 WebhookCall::create()
        ->url('https://senbaudfwq0ui.x.pipedream.net/')
        ->payload(['key' => 'value'])
        ->useSecret('sign-using-this-secret')
        ->dispatch();

 it returns 1 what is meaning of 1?

**Comment by freekmurze** [comment]
I guess that the job was successfully dispatched. It's more a question for the Laravel team.

**Comment by hamza-younas94** [comment]
@freekmurze do we have some kind of logs table just like in laravel webhook client ? this will be very helpful
