### ISSUE TITLE
Support for Laravel 5.8

### ISSUE THREAD

**Issue by yuval-a** [spatie/laravel-webhook-server#55]
Do you support Laravel 5.8.x?
Do any of the older versions do?
I keep getting version dependency errors from composer require - 
even when trying to install older versions.
What are the minimum requirements?

**Comment by freekmurze** [comment]
The current version doesn't support Laravel 7.0

Go check composer.json for the very first tag on this repo to see if we support 5.8 there.

**Comment by xlcrr** [comment]
Works fine for me on a laravel 5.8 project
