### ISSUE TITLE
Issuing a webhook call to a Laravel API test route always yields a timeout

### ISSUE THREAD

**Issue by yuval-a** [spatie/laravel-webhook-server#56]
Hi.
I have a test api route in a Laravel project, which leads to a controller method which simply logs the POST request's body, and returns success (HTTP code 200).
Simply sending a request to the route (e.g. with Postman) is successful - 
however - when I use the route as the url for the webhook, and use the package to send a webhook to it - 
I always get a timeout due to lack of response.

Are there any special considerations that needs to be taken care of when using a Laravel API route as an endpoint for the callback? Are there any specific headers that need to be sent to it?

**Comment by basherr** [comment]
@yuval-a The webhook should respond within the time period defined by your mailer service or otherwise it will fail.
