### ISSUE TITLE
Laravel V8 compatability

### ISSUE THREAD

**Issue by AndrewMoneronGenex** [spatie/laravel-webhook-server#58]
Problem 1
    - spatie/laravel-webhook-server 1.9.1 requires guzzlehttp/guzzle ^6.3 -> satisfiable by guzzlehttp/guzzle[6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.4.0, 6.4.1, 6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5, 6.5.x-dev] but these conflict with your requirements or minimum-stability.

**Comment by freekmurze** [comment]
I'll fix this tomorrow.
