### ISSUE TITLE
Guzzle vrsion missmatch when installing with Laravel 8

### ISSUE THREAD

**Issue by PHLAK** [spatie/laravel-webhook-server#59]
I see that support for Laravel 8 was added with commit c6ff94c84f61396312555819378d65eab2751cea, however it's still not possible to use v1.9.2 when upgrading to Laravel 8 due to a mismatch in required Guzzle versions. That is, the [Laravel 8 Upgrade Guide](https://laravel.com/docs/8.x/upgrade#updating-dependencies) instructs you to upgrade Guzzle to `^7.0.1` but laravel-webhook-server [requires Guzzle `^6.3`](https://github.com/spatie/laravel-webhook-server/blob/master/composer.json#L23).

```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for spatie/laravel-webhook-server ^1.9 -> satisfiable by spatie/laravel-webhook-server[1.9.0, 1.9.1, 1.9.2].
    - Can only install one of: guzzlehttp/guzzle[7.0.1, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[7.0.x-dev, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[7.1.x-dev, 6.5.x-dev].
    - Conclusion: install guzzlehttp/guzzle 6.5.x-dev
    - Installation request for guzzlehttp/guzzle ^7.0.1 -> satisfiable by guzzlehttp/guzzle[7.0.1, 7.0.x-dev, 7.1.x-dev].
```

**Comment by freekmurze** [comment]
I've just tagged a release with support for Guzzle 7.
