### ISSUE TITLE
Arabic Language not Supported

### ISSUE THREAD

**Issue by tayyab82977** [spatie/laravel-webhook-server#64]
I have added in header UTF8 but JSON response is coded.

 /*
     * These are the headers that will be added to all webhook requests.
     */
    'headers' => ['Content-Type' => 'application/json; charset=UTF-8',  'charset' => 'utf-8'],

**Comment by freekmurze** [comment]
I haven't come across this problem myself. I'd accept a PR with tests that fixes this.
