### ISSUE TITLE
Sort payload before JSON-encoding to prevent issue

### ISSUE THREAD

**Issue by sylouuu** [spatie/laravel-webhook-server#65]
Hi,

Thanks for this awesome package!

It's a common practice to sort keys of the array before JSON-encoding it and creating the signature.

Since you can't handle how the payload will be received, it's safer to force a sort by keys.

For example you send this:

```json
{
  "max_points": 100,
  "user_points": 70,
  "questions_count": 20,
  "right_answers_count": 14,
  "answered_questions_count": 20
}
```

Depending on the system/framework/luck/whatever, you are not sure to receive this payload in the same order, your framework may transform it, for example:

```json
{
  "user_points": 70, // swap
  "max_points": 100, // swap
  "questions_count": 20,
  "right_answers_count": 14,
  "answered_questions_count": 20
}
```

The signature will not be the same.

To prevent this, sort by keys (ksort) then send this:

```json
{
  "answered_questions_count": 20,
  "max_points": 100,
  "questions_count": 20,
  "right_answers_count": 14,
  "user_points": 70
}
```

Then you specify this sort in the documentation and all done, no potential signature fail check. :)

Best

**Comment by freekmurze** [comment]
Checking this now would be a breaking change I think.

I like the suggestion, and will take a look when creating a new major version of the package.

**Comment by judgej** [comment]
It does not matter what order the properties are sent in, so long as the signing algorithm knows what order to put *the data* into when calculating and checking the signature. So there is no reason to sort the payload - just be consistent with how the signing algorithm looks at the data.
