### ISSUE TITLE
Why depends on PHP v7.3

### ISSUE THREAD

**Issue by lidoma** [spatie/laravel-webhook-server#8]
Hi
The PHP v7.3 is almost the cutting edge version which not all cloud providers including mine support that. Is it possible to downgrade to PHP v7.2?

**Comment by freekmurze** [comment]
We're so minor PHP 7.3 functionalities in the code. We don't have a need for supporting PHP 7.2 anymore, so we're not going to invest time in this.

Feel free to fork this package and maintain your own PHP 7.2 compatible version.

**Comment by lidoma** [comment]
Ok. I create my own PHP 7.2 compatible version [here](https://github.com/lidoma/laravel-webhook-server).

https://github.com/lidoma/laravel-webhook-server
