### ISSUE TITLE
Unable to Listen any Event

### ISSUE THREAD

**Issue by adeel94mirza** [spatie/laravel-webhook-server#83]
Laravel **v7.10.3**
spatie/laravel-webhook-server **v1.12.0**
php **v7.4.3**

I am successfully able to send webhook but unable to listen to any events fired afterwards.

I have registered the events and listeners in the EventServiceProvider as well as turned on automatic discovery of Events/Listeners in Laravel

**Comment by davworkx** [comment]
Problems
    - spatie/laravel-webhook-server 1.4.0 requires guzzlehttp/guzzle ^6.3 -> found guzzlehttp/guzzle[6.3.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.3).
    - spatie/laravel-webhook-server[1.5.0, ..., 1.10.0] require php ^7.4 -> your php version (7.3.4) does not satisfy that requirement.
    - spatie/laravel-webhook-server[1.11.0, ..., 1.13.0] require php ^8.0|^7.4 -> your php version (7.3.4) does not satisfy that requirement.
    - Root composer.json requires spatie/laravel-webhook-server ^1.4 -> satisfiable by spatie/laravel-webhook-server[1.4.0, ..., 1.13.0].
