### ISSUE TITLE
Pass exception code to dispatchEvent()

### ISSUE THREAD

**Issue by adamlehmann** [spatie/laravel-webhook-server#9]
Wondering if you're open to including the exception code in `dispatchEvent`. Currently when listening for `WebhookCallFailedEvent` or `FinalWebhookCallFailedEvent` you are unable to get any details about what caused the failed event because `$event->response` will just be `null`. If `$exception->getCode()` could be passed through to the event as well then in an event listener you would be able to at least see what type of error occurred.

**Comment by freekmurze** [comment]
Feel free to send a PR for this with tests.
